# -*- coding: utf-8 -*-
"""Criando um sistema de reconhecimento facial do zero .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lh7EcLkA68p4t5sPZwfZB16IbN7THJuB
"""

# Instala bibliotecas necessárias
!pip install mtcnn
!pip install tensorflow
!pip install opencv-python
!pip install numpy
!pip install matplotlib

import cv2
import numpy as np
from mtcnn import MTCNN
import tensorflow as tf
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

# Detector de faces
detector = MTCNN()

# Modelo de reconhecimento (ex: FaceNet ou seu modelo treinado)
# Substitua "meu_modelo_de_reconhecimento.h5" pelo seu arquivo
model = load_model("meu_modelo_de_reconhecimento.h5")

# Função para normalizar e preparar face para classificação
def preprocess_face(face_img, target_size=(160,160)):
    face_img = cv2.resize(face_img, target_size)
    face_img = face_img.astype('float32') / 255.0
    face_img = np.expand_dims(face_img, axis=0)
    return face_img

def detect_and_recognize(image_path):
    # Carrega imagem
    image = cv2.imread(image_path)
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Detecta faces
    faces = detector.detect_faces(image_rgb)

    for face in faces:
        x, y, w, h = face['box']
        face_img = image_rgb[y:y+h, x:x+w]
        face_tensor = preprocess_face(face_img)

        # Predição (simulação de nome, adapte para seu modelo)
        pred = model.predict(face_tensor)
        nome = "Pessoa X"  # Aqui você converte pred para um nome real

        # Desenha retângulo e rótulo
        cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 2)
        cv2.putText(image, nome, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0,255,0), 2)

    # Converte para RGB para visualização com matplotlib
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(10,10))
    plt.imshow(image_rgb)
    plt.axis('off')
    plt.show()

# Substitua "imagem_teste.jpg" pela sua imagem
detect_and_recognize("imagem_teste.jpg")